# Generated by Django 3.1.5 on 2022-06-17 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='userPassword',
            field=models.BinaryField(null=True),
        ),
    ]
