# Generated by Django 3.1.5 on 2022-06-17 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='drinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('inStock', models.IntegerField(default=100)),
                ('maxStock', models.IntegerField(default=50)),
            ],
        ),
    ]
