# Generated by Django 3.1.5 on 2022-06-17 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendinghandler', '0002_drinks_imagename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinks',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
