# Generated by Django 3.1.5 on 2022-06-20 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendinghandler', '0005_auto_20220619_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drinks',
            name='id',
        ),
        migrations.AlterField(
            model_name='drinks',
            name='name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
